export const ADD_ITEM = 'ADD_ITEM';
export const CHECKLIST_ITEM_ADD = 'CHECKLIST_ITEM_ADD';
export const CREATE_ITEM_REQUESTED = 'CREATE_ITEM_REQUESTED';
export const ENTER_KEY_CODE = 13;
export const TOGGLE_CLICKED = 'TOGGLE_CLICKED';
export const DELETE_CLICKED = 'DELETE_CLICKED';
